# Generated by Django 3.0.4 on 2020-04-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='imageName',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
