# Generated by Django 3.0.4 on 2020-03-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_productimage'),
    ]

    operations = [
    ]
