# Generated by Django 3.0.4 on 2020-03-31 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20200331_1408'),
    ]

    operations = [
    ]
