# Generated by Django 3.0.4 on 2020-04-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20200331_1408'),
    ]

    operations = [
    ]
