# Generated by Django 3.0.5 on 2020-04-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_contact',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name_contact',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name_contact',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message_contact',
            new_name='message',
        ),
    ]
