# Generated by Django 3.0.4 on 2020-04-23 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20200418_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='solved_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
