# Generated by Django 3.0.4 on 2020-04-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_product_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mainImage',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
    ]
