# Generated by Django 3.0.4 on 2020-04-28 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
    ]
