# Generated by Django 3.0.4 on 2020-04-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_product_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mainImage',
        ),
    ]
