# Generated by Django 3.0.6 on 2021-07-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_remove_product_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Foods', 'Foods'), ('Drinks', 'Drinks'), ('Home & Cleaning', 'Home & Cleaning'), ('Baby Care', 'Baby Care'), ('Sports & Nutrition', 'Sports & Nutrition'), ('Pet Care', 'Pet care'), ('Others', 'Others')], default='Others', max_length=120),
        ),
    ]
