# Generated by Django 3.0.4 on 2020-04-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
