# Generated by Django 3.0.4 on 2020-04-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200427_1723'),
    ]

    operations = [
    ]
