# Generated by Django 3.0.4 on 2020-04-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200427_2254'),
    ]

    operations = [
    ]
